# stage 1 in the docker multi-stage build, called 'build'

FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore

# copy and publish app and libraries
COPY . ./
RUN dotnet publish -c release -o /app --no-restore

# final stage/image in the docker multi-stage build
FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine
WORKDIR /app
COPY --from=build /app .
EXPOSE 80 443
ENTRYPOINT ["dotnet", "rp1.dll"]